package br.com.gestaodireta.harvest.enumeration;

public enum HarvestSeasonComparisonMetric {
    AREA_HECTARES,
    PLANNED_COST,
    PLANNED_REVENUE,
    PLANNED_RESULT,
    PLANNED_MARGIN,
    PROJECTED_COST,
    PROJECTED_REVENUE,
    PROJECTED_PROFIT,
    PROJECTED_MARGIN,
    REALIZED_COST,
    REALIZED_REVENUE,
    REALIZED_PROFIT,
    REALIZED_MARGIN,
    PLANNED_COST_PER_HECTARE,
    PLANNED_REVENUE_PER_HECTARE,
    PLANNED_RESULT_PER_HECTARE,
    PROJECTED_COST_PER_HECTARE,
    PROJECTED_REVENUE_PER_HECTARE,
    PROJECTED_PROFIT_PER_HECTARE,
    REALIZED_COST_PER_HECTARE,
    REALIZED_REVENUE_PER_HECTARE,
    REALIZED_PROFIT_PER_HECTARE
}
